version = 1

# Git ve config dosyaları
[[annotations]]
path = [
  ".gitignore",
  ".gitattributes",
  ".gitmodules",
  ".github/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = ["launcher/package/**"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

# Docs & markdown
[[annotations]]
path = ["**/*.md", "doc/**"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Project Tick"

# Build / cmake
[[annotations]]
path = ["cmake/**", "**/CMakeLists.txt"]
SPDX-License-Identifier = "BSD-3-Clause"
SPDX-FileCopyrightText = "Various authors"

# Assets (png/svg/icon vs)
[[annotations]]
path = [
  "branding/**",
  "launcher/resources/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Project Tick"

# Test data
[[annotations]]
path = [
  "**/testdata/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = ["**/*.ui"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["libraries/**/.gitignore"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"
