// SPDX-FileCopyrightText: 2026 Project Tick
// SPDX-FileContributor: Project Tick
// SPDX-License-Identifier: Apache-2.0

pragma Singleton

import QtQuick

/*
 * Lookup for the original pixel-art PNGs under art/ (see art/generate.py --
 * every file here is procedurally generated by that checked-in script, never
 * at runtime), the same shape as Icons.qml's url() for SVGs.
 *
 * landscapeUrl() is the one callers reach for most: CoverArt's fallback art,
 * PlayDock's photo-less bar and Home's jump cards all pick one of 24
 * generated scenes by hashing the instance/world id, so a given item always
 * draws the same scene rather than a new one on every repaint
 * (design-plan.md §6 "fallback covers": bounded and designed, not
 * random-looking). Each scene exists at three shapes -- "card", "band" and
 * "strip" -- because a 16:9 scene cropped into a 12:1 dock bar only ever
 * shows a sliver of plain sky; shapeForAspect() picks the one that fits its
 * host. landscapeMirror() then flips roughly half of the hashed ids, which
 * doubles the number of distinct looks for free.
 *
 * blockUrlFor() serves the 16x16 block textures the same way, for the small
 * square spots (a world's icon) where a whole scene would only be a smear.
 */
QtObject {
    readonly property int sceneCount: 24
    readonly property var blockNames: [
        "grass_side", "dirt", "stone", "cobblestone", "oak_planks",
        "deepslate", "sand", "gravel", "grass_top"
    ]
    readonly property string _root: "qrc:/qt/qml/MeshMC/Components/art/"

    // A plain, fast string hash (djb2-ish) -- only needs to be stable across
    // calls in this process, never to match anything outside QML.
    function _hash(text) {
        var h = 5381
        for (var i = 0; i < text.length; ++i)
            h = ((h * 33) ^ text.charCodeAt(i)) >>> 0
        return h
    }

    function _key(seed) {
        return seed && seed.length > 0 ? seed : "mesh"
    }

    // "card" (about 16:9), "band" (about 5:1) or "strip" (about 12:1) --
    // whichever of the three generated shapes a host of this width/height
    // ratio would crop the least.
    function shapeForAspect(aspect) {
        return aspect > 8 ? "strip" : aspect > 3 ? "band" : "card"
    }

    // @p seed is normally an instance or world id; "" still returns a valid,
    // stable pick rather than an empty source. @p shape is one of
    // shapeForAspect()'s three names (default "card").
    function landscapeUrl(seed, shape) {
        var idx = _hash(_key(seed)) % sceneCount
        return _root + "landscapes/" + (shape || "card") + "/" + (idx < 10 ? "0" : "") + idx + ".png"
    }

    // Whether this seed's landscape is drawn flipped left-to-right. Uses a
    // different bit of the hash than landscapeUrl()'s index, so the two
    // choices do not correlate.
    function landscapeMirror(seed) {
        return ((_hash(_key(seed)) >>> 9) & 1) === 1
    }

    // @p name is one of art/blocks/*.png without its extension, e.g. "dirt".
    function blockUrl(name) {
        return _root + "blocks/" + name + ".png"
    }

    // A block texture picked by hashing @p seed -- a stable, generic icon for
    // a world that has none of its own.
    function blockUrlFor(seed) {
        return blockUrl(blockNames[_hash(_key(seed)) % blockNames.length])
    }

    // AmbientPattern's own tileable wash: a dirt/deepslate checkerboard
    // pre-converted to a luminance alpha mask (see generate.py's
    // ambient_tile()), so IconImage's alpha-channel recolouring -- the same
    // mechanism MeshIcon.qml already uses for every SVG icon -- can tint it
    // to any palette colour at draw time.
    function ambientMaskUrl() {
        return _root + "ambient/blocks_mask.png"
    }

    function heroUrl() {
        return _root + "hero/home_hero.png"
    }

    // @p kind is one of art/empty/*.png without its extension, e.g. "no_worlds".
    function emptyUrl(kind) {
        return _root + "empty/" + kind + ".png"
    }
}
