name: Build Translations and Serve

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install host dependencies
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
            gettext

      - name: Install Qt
        if: ${{ inputs.msystem == '' }}
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          version: 6.10.2
          modules: qtimageformats qtnetworkauth
          archive: qtbase qttools
          cache: false

      - name: Build translations
        run: ./launcher/scripts/release.sh

      - name: Move directory
        run: |
          mv build-translations _site
          cp .github/CNAME _site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
