/* SPDX-FileCopyrightText: 2026 Project Tick
 * SPDX-FileContributor: Project Tick
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (C) 2026 Project Tick
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <minecraft/VersionFile.h>
#include <minecraft/PackProfile.h>
#include <minecraft/Library.h>
#include <QJsonDocument>
#include <ProblemProvider.h>

class OneSixVersionFormat
{
  public:
	// version files / profile patches
	static VersionFilePtr versionFileFromJson(const QJsonDocument& doc,
											  const QString& filename,
											  const bool requireOrder);
	static QJsonDocument versionFileToJson(const VersionFilePtr& patch);

	// libraries
	static LibraryPtr libraryFromJson(ProblemContainer& problems,
									  const QJsonObject& libObj,
									  const QString& filename);
	static QJsonObject libraryToJson(Library* library);

	// DEPRECATED: old 'plus' jar mods generated by the application
	static LibraryPtr plusJarModFromJson(ProblemContainer& problems,
										 const QJsonObject& libObj,
										 const QString& filename,
										 const QString& originalName);

	// new jar mods derived from libraries
	static LibraryPtr jarModFromJson(ProblemContainer& problems,
									 const QJsonObject& libObj,
									 const QString& filename);
	static QJsonObject jarModtoJson(Library* jarmod);

	// mods, also derived from libraries
	static LibraryPtr modFromJson(ProblemContainer& problems,
								  const QJsonObject& libObj,
								  const QString& filename);
	static QJsonObject modtoJson(Library* jarmod);
};
